// generated by Fast Light User Interface Designer (fluid) version 1.0301

#ifndef main_h
#define main_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
extern Fl_Group *_pTopGrp;
#include <FL/Fl_Box.H>
#include <FL/Fl_Input.H>
extern Fl_Input *_pAuftrag;
extern Fl_Input *_pVertrag;
extern Fl_Group *_pDummy3;
#include <FL/Fl_Choice.H>
extern Fl_Choice *_pKunde;
extern Fl_Group *_pDummy;
extern Fl_Float_Input *_pEinzelpreis;
extern Fl_Int_Input *_pAnzahl;
#include <FL/Fl_Output.H>
extern Fl_Output *_pGesamt;
extern Fl_Float_Input *_pTagesmiete;
extern Fl_Int_Input *_pJahreLaufzeit;
extern Fl_Float_Input *_pRueckkaufswert;
extern Fl_Group *_pDummy2;
extern Fl_Input *_pMietbeginn;
#include <FL/Fl_Button.H>
extern Fl_Button *_pBtnRenditeOhneSteuer;
extern Fl_Button *_pBtnRenditeMitSteuer;
extern Fl_Output *_pRenditeOhneSteuer;
extern Fl_Output *_pRenditeMitSteuer;
extern Fl_Group *_pDummy4;
extern Fl_Button *_pBtnInListe;
extern Fl_Button *_pBtnVertragEdit;
extern Fl_Group *_pBottomGrp;
extern Flx_Table *_pTable;
#endif
