// generated by Fast Light User Interface Designer (fluid) version 1.0301

#include "main.h"

Fl_Group *_pTopGrp=(Fl_Group *)0;

Fl_Input *_pAuftrag=(Fl_Input *)0;

Fl_Input *_pVertrag=(Fl_Input *)0;

Fl_Group *_pDummy=(Fl_Group *)0;

Fl_Float_Input *_pEinzelpreis=(Fl_Float_Input *)0;

Fl_Int_Input *_pAnzahl=(Fl_Int_Input *)0;

Fl_Output *_pGesamt=(Fl_Output *)0;

Fl_Float_Input *_pTagesmiete=(Fl_Float_Input *)0;

Fl_Int_Input *_pJahreLaufzeit=(Fl_Int_Input *)0;

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(574, 399);
    w = o;
    o->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { _pTopGrp = new Fl_Group(10, 10, 555, 280);
      _pTopGrp->box(FL_BORDER_BOX);
      _pTopGrp->color(FL_LIGHT2);
      { Fl_Group* o = new Fl_Group(20, 22, 535, 51);
        o->box(FL_BORDER_BOX);
        o->color(FL_LIGHT2);
        o->labelcolor((Fl_Color)4);
        { new Fl_Box(25, 39, 60, 16, "Auftrag: ");
        } // Fl_Box* o
        { Fl_Box* o = new Fl_Box(216, 36, 60, 22, "Vertrag: ");
          o->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
        } // Fl_Box* o
        { _pAuftrag = new Fl_Input(106, 32, 100, 29);
          _pAuftrag->box(FL_PLASTIC_THIN_DOWN_BOX);
        } // Fl_Input* _pAuftrag
        { _pVertrag = new Fl_Input(276, 32, 105, 29);
          _pVertrag->box(FL_PLASTIC_THIN_DOWN_BOX);
        } // Fl_Input* _pVertrag
        o->end();
      } // Fl_Group* o
      { _pDummy = new Fl_Group(200, 75, 15, 15);
        _pDummy->end();
      } // Fl_Group* _pDummy
      { Fl_Group* o = new Fl_Group(20, 85, 535, 100, "Container");
        o->box(FL_BORDER_BOX);
        o->color(FL_LIGHT2);
        o->labeltype(FL_SHADOW_LABEL);
        o->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
        { new Fl_Box(25, 118, 80, 16, "Einzelpreis: ");
        } // Fl_Box* o
        { _pEinzelpreis = new Fl_Float_Input(106, 112, 100, 29);
          _pEinzelpreis->box(FL_PLASTIC_THIN_DOWN_BOX);
          _pEinzelpreis->color(FL_BACKGROUND2_COLOR);
          _pEinzelpreis->selection_color(FL_SELECTION_COLOR);
          _pEinzelpreis->labeltype(FL_NORMAL_LABEL);
          _pEinzelpreis->labelfont(0);
          _pEinzelpreis->labelsize(14);
          _pEinzelpreis->labelcolor(FL_FOREGROUND_COLOR);
          _pEinzelpreis->align(Fl_Align(FL_ALIGN_LEFT));
          _pEinzelpreis->when(FL_WHEN_RELEASE);
        } // Fl_Float_Input* _pEinzelpreis
        { Fl_Box* o = new Fl_Box(216, 117, 59, 16, "Anzahl:");
          o->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
        } // Fl_Box* o
        { _pAnzahl = new Fl_Int_Input(276, 111, 74, 29);
          _pAnzahl->box(FL_PLASTIC_THIN_DOWN_BOX);
          _pAnzahl->color(FL_BACKGROUND2_COLOR);
          _pAnzahl->selection_color(FL_SELECTION_COLOR);
          _pAnzahl->labeltype(FL_NORMAL_LABEL);
          _pAnzahl->labelfont(0);
          _pAnzahl->labelsize(14);
          _pAnzahl->labelcolor(FL_FOREGROUND_COLOR);
          _pAnzahl->align(Fl_Align(FL_ALIGN_LEFT));
          _pAnzahl->when(FL_WHEN_RELEASE);
        } // Fl_Int_Input* _pAnzahl
        { Fl_Box* o = new Fl_Box(371, 117, 64, 16, "Gesamt:");
          o->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
        } // Fl_Box* o
        { _pGesamt = new Fl_Output(441, 112, 95, 25);
        } // Fl_Output* _pGesamt
        { new Fl_Box(25, 151, 80, 16, "Tagesmiete:");
        } // Fl_Box* o
        { _pTagesmiete = new Fl_Float_Input(106, 145, 100, 29);
          _pTagesmiete->box(FL_PLASTIC_THIN_DOWN_BOX);
          _pTagesmiete->color(FL_BACKGROUND2_COLOR);
          _pTagesmiete->selection_color(FL_SELECTION_COLOR);
          _pTagesmiete->labeltype(FL_NORMAL_LABEL);
          _pTagesmiete->labelfont(0);
          _pTagesmiete->labelsize(14);
          _pTagesmiete->labelcolor(FL_FOREGROUND_COLOR);
          _pTagesmiete->align(Fl_Align(FL_ALIGN_LEFT));
          _pTagesmiete->when(FL_WHEN_RELEASE);
        } // Fl_Float_Input* _pTagesmiete
        { Fl_Box* o = new Fl_Box(216, 151, 59, 16, "Laufzeit:");
          o->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
        } // Fl_Box* o
        { _pJahreLaufzeit = new Fl_Int_Input(276, 145, 29, 29);
          _pJahreLaufzeit->box(FL_PLASTIC_THIN_DOWN_BOX);
          _pJahreLaufzeit->color(FL_BACKGROUND2_COLOR);
          _pJahreLaufzeit->selection_color(FL_SELECTION_COLOR);
          _pJahreLaufzeit->labeltype(FL_NORMAL_LABEL);
          _pJahreLaufzeit->labelfont(0);
          _pJahreLaufzeit->labelsize(14);
          _pJahreLaufzeit->labelcolor(FL_FOREGROUND_COLOR);
          _pJahreLaufzeit->align(Fl_Align(FL_ALIGN_LEFT));
          _pJahreLaufzeit->when(FL_WHEN_RELEASE);
        } // Fl_Int_Input* _pJahreLaufzeit
        { Fl_Box* o = new Fl_Box(305, 151, 59, 16, "Jahre");
          o->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
        } // Fl_Box* o
        o->end();
      } // Fl_Group* o
      _pTopGrp->end();
    } // Fl_Group* _pTopGrp
    o->end();
  } // Fl_Double_Window* o
  w->show(argc, argv);
  return Fl::run();
}
